apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-argocd-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/squoc/arc-argocd-deploy'
        revision: HEAD
        files:
          - path: 'value-files/*.yaml'
  template:
    metadata:
      name: '{{namespace}}-system'
    spec:
      project: default
      source:
        path: 'charts/actions-runner-controller'
        repoURL: 'https://github.com/squoc/arc-argocd-deploy'
        targetRevision: HEAD
        helm:
          releaseName: "{{deploymentName}}"
          valueFiles:
            - values.yaml
            - '../../value-files/{{path.filename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
