apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-argocd-deploy
spec:
  generators:
  - list:
      elements:
      - namespace: customer1
  template:
    metadata:
      name: '{{namespace}}-arc'
    spec:
      project: default
      source:
        repoURL: https://actions-runner-controller.github.io/actions-runner-controller.git
        targetRevision: HEAD
        helm:
          releaseName: arc-argocd-deploy
          valueFiles:
            - values-{{namespace}}.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
