apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-argocd-deploy
spec:
  generators:
  - list:
      elements:
      - namespace: customer1
  template:
    metadata:
      name: '{{namespace}}-arc'
    spec:
      project: default
      source:
        path: charts
        repoURL: https://github.com/squoc/arc-argocd-deploy
        targetRevision: HEAD
        helm:
          releaseName: arc-argocd-deploy
          valueFiles:
            - values.yaml
            - values-{{namespace}}.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
